USE master
GO

ALTER TABLE Users
DROP CONSTRAINT PK_Id_Username

ALTER TABLE Users
ADD CONSTRAINT [PK_Id]
PRIMARY KEY (Id)

ALTER TABLE Users
ADD CONSTRAINT CHK_UsernameLength CHECK (LEN([Username])>=3);

INSERT INTO Users
VALUES
('Desi', 'pass123', NULL, CURRENT_TIMESTAMP, 0);